import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";

export default function Test() {
  const router = useRouter();
  const newsId = router.query.newsId;
  console.log(newsId);

  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{newsId}</h1>
      </main>
    </div>
  );
}
